version: "3.7"

services:
  itb:
    build: compose/production/itb
    container_name: generic-validator
    ports:
      - 9090:8080
    networks:
      - mydefault

  validator-api:
    container_name: validator-api
    build:
      context: .
      dockerfile: compose/dev/api/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - ${VALIDATOR_API_PORT}:${VALIDATOR_API_PORT}
    env_file: compose/dev/api/.dev
    networks:
      - mydefault

  validator-ui:
    container_name: validator-ui
    build:
      context: .
      dockerfile: compose/dev/ui/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - ${VALIDATOR_UI_PORT}:${VALIDATOR_UI_PORT}
    env_file: compose/dev/ui/.dev
    networks:
      - mydefault


networks:
  mydefault:
    name: globalnet