version: "3.7"

services:
  itb:
    build: docker/itb
    container_name: generic-validator
    ports:
      - 9090:8080
    networks:
      - mydefault

  validator-api:
    container_name: validator-api
    image: meaningfy/rdf-validator-ws-api:latest
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - ${VALIDATOR_API_PORT}:${VALIDATOR_API_PORT}
    env_file: docker/.env
    networks:
      - mydefault

  validator-ui:
    container_name: validator-ui
    image: meaningfy/rdf-validator-ws-ui:latest
    build:
      context: .
      dockerfile: docker/ui/Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - ${VALIDATOR_UI_PORT}:${VALIDATOR_UI_PORT}
    env_file: docker/.env
    depends_on:
      - "validator-api"
    networks:
      - mydefault


networks:
  mydefault:
    name: globalnet