version: "3.7"

services:
  maintainance:
    container_name: maintainance
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx:/usr/share/nginx/html
    networks:
      - mydefault

  itb:
    build: itb
    container_name: generic-validator
    ports:
      - 9090:8080
    networks:
      - mydefault

  validator-api:
    container_name: validator-api
    image: meaningfy/rdf-validator-ws-api:latest
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ..:/usr/src/app
      - rdf-validator-template:${RDF_VALIDATOR_TEMPLATE_LOCATION}
      - rdf-validator-shacl-shapes:${RDF_VALIDATOR_SHACL_SHAPES_PATH}
    ports:
      - ${RDF_VALIDATOR_API_PORT}:${RDF_VALIDATOR_API_PORT}
    env_file: .env
    networks:
      - mydefault

  validator-ui:
    container_name: validator-ui
    image: meaningfy/rdf-validator-ws-ui:latest
    build:
      context: ..
      dockerfile: ./docker/ui/Dockerfile
    volumes:
      - ..:/usr/src/app
    ports:
      - ${RDF_VALIDATOR_UI_PORT}:${RDF_VALIDATOR_UI_PORT}
    env_file: .env
    depends_on:
      - "validator-api"
    networks:
      - mydefault

volumes:
  rdf-validator-template:
    external: true
  rdf-validator-shacl-shapes:
    external: true

networks:
  mydefault:
    name: globalnet